### PR TITLE
Replace band color scaling equation

### PR DESCRIPTION
**Pull request by innovate-invent**

### CODE REVIEW

**Review by bfjia — APPROVED** [review]

**Comment by bfjia** [comment]
@innovate-invent one of the staus called build seem to broken. Can you please take a look at what's happening? Thanks!

**Comment by innovate-invent** [comment]
I am not sure what is happening, you need someone with admin rights to override the merge.

**Comment by bfjia** [comment]
Where is the build step being done? I can take a look to troubleshoot

**Comment by bfjia** [comment]
There are 2 checks that needs to be done. The cloudflare pages one had succeeded but I'm not sure what the "build" action is without permission to view the settings for this repo. It's not reporting anything, and I dont think that's related to cloudflare. 

Sorry to be bothering you, this is relatively urgent as it's part of the manuscript submission that we aim to get done before the holidays. However, we can push to the new year if needed should we run into issues.

**Comment by cookersjs** [comment]
No problem - funnily enough, my plans got delayed a little bit today so I can try and look into what the build step is supposed to be reporting and then if nothing looks off I can merge it - I will give you an update shortly

**Comment by cookersjs** [comment]
OK @bfjia I am pretty sure this build step has always been this way. I can't find anything really about _what_ it is checking/building, but the Cloudflare Pages step, which actually builds and deploys a version of this branch was successful. If you look at previous merges of other branches, you can see they either always had 1/2 checks complete, or (in earlier cases) the checks failed. Seems this is just how things are, haha

I think we are good to merge - just give me the final 👍 and I'll go ahead and do that

**Comment by cookersjs** [comment]
Lol OK it was just a random setting that was checked on in the repo settings that was for branches to 'require status check before merging', but it wasn't actually configured to check a specific source - which I assume is why it was waiting for a response (from nowhere). I turned it off, because I don't think it had much point right now, and this will prevent future confusion

**Comment by bfjia** [comment]
Merged! Thank you for your assistance

**Comment by fionabrinkman** [comment]
Thank you guys! 

Just to be clear though, can we avoid automatic changes occurring after we get a final version? We have had issues with automated updates occurring breaking things for GlobeCorr and IslandCompare, and so doing updates when we are ready to do them and test all is OK would be great. Perhaps that “check” was related to this, though funny that it was going to nowhere! (Perhaps to something involving Nolan before??). 

Regardless, a huge thanks for the quick replies! 

Best wishes,
Fiona


__

Dr. Fiona S. L. Brinkman (she/her), PhD FRSC
Distinguished Professor, 
Dept. Molecular Biology and Biochemistry. Office: SSB 7110
Associate Professor, School of Computing Science,
and Faculty of Health Sciences
Simon Fraser University, Burnaby, BC, Canada
brinkmanlab.ca 

I respectfully acknowledge the unceded traditional territories of the Coast Salish peoples, including the səl̓ilw̓ətaʔɬ (Tsleil-Waututh), kʷikʷəƛ̓əm (Kwikwetlem), Sḵwx̱wú7mesh Úxwumixw (Squamish) and xʷməθkʷəy̓əm (Musqueam) Nations upon which I reside.

**Comment by cookersjs** [comment]
As best as I can tell, Cloudflare is set up to create a preview version with the new changes that can be tested before the branch is merged (this automated comment from Cloudflare contains the preview link: https://github.com/brinkmanlab/globecorr/pull/31#issuecomment-1355941803) . I think we can use that to check if there are any breaking changes introduced beforehand. 

The other 'check' that I turned off was basically a red herring that made it seem like something was off, when really it was just that it wasn't checking anything. The result was a concerning 'only 1/2 checks passed' message for this merge, but the missing check wasn't actually configured to do anything. So 1/1 *actual* checks passed 👍, and 0/1 improperly setup checks passed. I noticed as well that earlier merges for globecorr also had the same situation, which was the final thing that made me assume it was OK to merge.

Hope that all makes sense! Enjoy your trip :)

**Pull request merged**
